# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'salesreg' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for salesreg
  pod 'Paystack'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  target 'salesregTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'salesreg-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for salesreg-tvOS

  target 'salesreg-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
